Shield Reworks
echo-station/echo-station pull request #80
Opened 2024-08-15 15:04 UTC by ProphetCrow

## About the PR
Reopens (https://github.com/echo-station/echo-station/pull/37)

## Why / Balance
Shields are very brittle and will shatter way before the user goes into a critical state, regardless if the user was using the supposedly correct shield for the correct damage type. This PR ultimately seeks to make shields a more useful tool with an ultimately longer shelf life, with respect to their niche specialization.

Shields now are able to be stored in backpacks, consuming a 5x3 grid (taller than wide). This idea is ultimately aimed towards user ergonomics and quality of life, because without this change, you would need to sacrifice a hand slot to bring a shield with you to any environment.
Further justification: The Energy shield and the telescopic shield are able to be stored in a backpack while deployed, and they consume a 4x4 grid, which is also the same size as a blood-red hardsuit and most large weapons.
This change is also aimed towards a future weapon size rebalance which will aim to convert most rifle sized weapons to 5x2 grid slots.

**Changelog**
:cl:
- tweak: Shield stats have been modified

2024-08-18 14:20 UTC, redmushie commented
Please fix the failing checks, then I can merge it. Thanks!

2024-08-21 15:01 UTC, redmushie commented
Please add Echo markers, preferably at the first line of your changes if possible, so I know what the reason for the change is / what to change when I merge upstream changes

2024-08-21 15:01 UTC, redmushie requested changes
Please add Echo markers, preferably at the first line of your changes if possible, so I know what the reason for the change is / what to change when I merge upstream changes

2024-08-21 15:49 UTC, ProphetCrow commented
see 33d22aa

2024-08-21 16:01 UTC, redmushie requested changes

2024-08-21 16:01 UTC, redmushie commented on Resources/Prototypes/Entities/Objects/Shields/shields.yml
> +          Blunt: 1
Marker

2024-08-21 16:01 UTC, redmushie commented on Resources/Prototypes/Entities/Objects/Shields/shields.yml
> +          Heat: 2
Marker

2024-08-21 16:01 UTC, redmushie commented on Resources/Prototypes/Entities/Objects/Shields/shields.yml
> +          Blunt: 1.5
Marker

2024-08-21 16:15 UTC, redmushie reviewed
LGTM!

2024-08-21 16:25 UTC, redmushie approved these changes

2024-08-21 16:32 UTC, merged