Rifles - Grid inventory adjustments
echo-station/echo-station pull request #86
Opened 2024-08-20 21:50 UTC by ProphetCrow

## About the PR

This is an adjustment for the majority of ranged weapons that are larger than a pistol.
In their current state, **most** firearms, including lasers, consume an ergonomically oppressive and nonsensical 4x4 block, with a handful of notable exceptions that stray from this law.
This PR aims to realistically standardize the weapon sizes with respect to the weapons that already have a defined size (notably, the C20-R)

## Why / Balance
This standardizes the size of firearms. SMGs, such as the C-20r, were already 4x2, so this gets the rest of the weapons up to a similar playing field with sensible size adjustments. Most rifle sized weapons are **longer than they are wide** so a 4x4 does not accurately reflect how they should consume backpack space. 

Notable changes
Most long rifles (LRs) and laser rifles (lasers) are defined to be 5x2, which is slightly longer than the average submachine gun
Shotguns have been updated to match the general size of an LR. Shotguns, such as the Kammerer, now take up 5x2 instead of 5x1. 
Heavier weapons, such as the L6 saw, consume a 5x3 block to indicate its greater bulk
Snipers and bolt action weapons are longer than modern long rifles, so they consume 6x2

Overall, this makes rifles easier to store in backpacks, but there's an existing precedent for estimated weapon sizes when you consider the current backpack size of the Kammerer and the C20-R. 

## Media 

https://discord.com/channels/1263024087647649853/1263031053627428885/1275556221813784576
and below traffic

**Changelog**

:cl: Crow
- tweak: Adjusted grid inventory sizes for rifles

2024-08-21 14:57 UTC, redmushie requested changes

2024-08-21 14:57 UTC, redmushie commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  - type: Item
Add Echo marker `# Echo: Decrease size` or similar

2024-08-21 14:57 UTC, redmushie commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  - type: Item
Add Echo marker w/ brief description

2024-08-21 14:57 UTC, redmushie commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  - type: Item
Add Echo marker w/ brief description

2024-08-21 14:57 UTC, redmushie commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  - type: Item
Add Echo marker w/ brief description

2024-08-21 14:57 UTC, redmushie commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
> +    shape:
Add Echo marker w/ brief description

2024-08-21 14:57 UTC, redmushie commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
> +    shape:
Add Echo marker w/ brief description

2024-08-21 14:57 UTC, redmushie commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
> +    shape:
Add Echo marker w/ brief description

2024-10-08 16:36 UTC, ProphetCrow commented
wang-jangled my text editor and managed to get it merged and updated. went back and added echo markers at the requested spots.

2024-10-08 16:46 UTC, redmushie approved these changes

2024-10-08 16:48 UTC, merged